### ISSUE TITLE
Why the double negatives?

### ISSUE THREAD

**Issue by mbakkokom** [raingloom/interlu#7]
Why the double negatives on `init.lua` at line 23?

`return not not err:match( 'expected.-near %<eof%>%s*$' )`

Why not just: `return err:match( 'expected.-near %<eof%>%s*$' )`?

**Comment by raingloom** [comment]
It's a trick I saw some more experienced Lua users, erm, use. It converts a "truthy" value to a boolean. The function in question answers a true/false question about an error message, so it is expected to return a boolean.

`string.match` returns either a string _(well, it returns strings and numbers, according to the matches specified in the regex string)_ or nil, this is a fast and compact way to make that nil into a `false` and throw away the string, so it can be garbage collected.

This is not as important for simple use-cases, but it's important to keep the results within expectations, because someone - even myself a few months later - might come back to it and do something crazy that only works with booleans and won't realize what's going wrong until I look at the source and realize I'm not getting a boolean, but either a nil or a string.

I hope that answers it.

**Comment by pablomayobre** [comment]
I have also seen a `tobool` function implemented this way:
```lua
local tobool = function (a)
  return not not a
end
```
Note that giving this function a name makes the code more readable:
```lua
return tobool(err:match( 'expected.-near %<eof%>%s*$' ))
```
But it wouldn't be worth it if it's used once in the entire code

**Comment by raingloom** [comment]
Such a simple expression doesn't really need a separate function IMO, PUC Lua does no bytecode optimizations and functions actually have a decent memory and speed overhead. Just like one wouldn't write a squaring function and wouldn't use the `^` operator to square either, the double negation is a simple enough pattern to not necessitate an extra function.

I can't remember the exact figures, but I once tested out if empty functions or empty tables were better for creating UIDs and functions were (a lot) more than twice as memory hungry.

**Comment by pablomayobre** [comment]
Yes they are, they allocate a complete scope, locals, upvalues, code, argument references and much more, they are complex!

Yet speed shouldn't be that much of a concern (I always prefer code readability over faster code) except when in a bottleneck, slowdown or a real performance constraint. The later may be your case since you probably want to make the layer as slim as possible

**Comment by raingloom** [comment]
Yup, I wanted this thing to be embeddable into anything, even on very limited platforms.

And tbh it's not really the speed overhead, it's the memory that bothers me.
